import m2py as mp
makergear = mp.mopen('COM7',115200)
mp.speed(makergear, 2400)
mp.home(makergear)
mp.coord(makergear, coord = 'rel')
mp.coord(makergear, coord = 'abs')
mp.move(makergear)
mp.move(makergear, x = 10)
mp.move(makergear, x = 10, y = 20, z = -5)
mp.move(makergear, z = -20)
mp.speed(makergear, 1600)
mp.home(makergear, 'X Y')
mp.mclose(makergear)